### ISSUE TITLE
The examples are bounded to Jersey: how to use them with OpenLiberty

### ISSUE THREAD

**Issue by borgogelli** [agrestio/agrest-examples#1]
I would like to migrate the example project from Jersey to OpenLiberty. The problem is in the [Application.class](https://github.com/agrestio/agrest-examples/blob/main/agrest5-jaxrs3-cayenne/src/main/java/io/agrest/example/Application.java) where the two last methods calls are bounded to the ResourceConfig Jersey's class.

(https://stackoverflow.com/questions/79148968/migrate-from-jersey-to-openliberty#79148968)

**Comment by andrus** [comment]
There has to be an OpenLiberty-specific solution for explicitly configuring features and resources, though I can't seem to find any docs. 

My default hypothesis based on JAX-RS 3 specification, is that both resources (API endpoints) and features should be auto-discoverable. Resources - by the `@Path` annotation (so this may actually work already). But features will require a `@Provider` annotation. Agrest feature doesn't have this annotation, but you can create your own custom feature and use it to register Agrest stuff:

```java
@Provider
public class MyFeature implements Feature {
     public boolean configure(FeatureContext context) {

       ServerRuntime cayenneRuntime = ServerRuntime.builder()
                .addConfig("cayenne-project.xml")
                .build(); 

        AgCayenneModule cayenneModule = AgCayenneBuilder.build(cayenneRuntime);
        AgRuntime runtime = AgRuntime.builder().module(cayenneModule).build();
        AgJaxrsFeature feature = AgJaxrsFeature.builder().runtime(runtime).build();

        context.register(feature);
     }
}
```

If this doesn't work, please ask the OpenLiberty community directly.

**Comment by borgogelli** [comment]
You are a genius, it works perfectly.  Below is the code adapted to version 5.x of Agrest, tested on OpenLiberty 24

I have been using your creations in my work with great satisfaction for 20 years.
Perhaps your weak point is personal marketing, because you deserve much more fame and your products more diffusion.
Greetings from Italy.

```
import jakarta.ws.rs.core.Feature;
import jakarta.ws.rs.core.FeatureContext;
import jakarta.ws.rs.ext.Provider;
import io.agrest.cayenne.AgCayenneModule;
import io.agrest.jaxrs3.AgJaxrsFeature;
import io.agrest.runtime.AgRuntime;
import org.apache.cayenne.configuration.server.ServerRuntime;

@Provider
public class MyFeature implements Feature {
	
     public boolean configure(FeatureContext context) {
       ServerRuntime cayenneRuntime = ServerRuntime.builder()
                .addConfig("cayenne-project.xml")
                .build(); 
        AgCayenneModule cayenneModule = AgCayenneModule.build(cayenneRuntime);        
        AgRuntime runtime = AgRuntime.builder().module(cayenneModule).build();
        AgJaxrsFeature feature = AgJaxrsFeature.builder(runtime).build();
        context.register(feature);        
        return true;
     }
}
```

**Comment by andrus** [comment]
Glad it worked, and thanks for the kind words 🙂  We are trying. I just had two DFLib presentations in Italy in September. Here is one of them in Milan: https://www.youtube.com/watch?v=1P1UtWxwdYM&t=551s
